site_name: Core QA Edgio Console App
site_dir: public
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    scheme: limelight
  features:
    - navigation.instant
    - navigation.tabs
  icon:
    repo: material/gitlab
  font:
    text: Lato
extra_css:
  - stylesheets/global.css
extra_javascript:
  - https://unpkg.com/mermaid@8.13.5/dist/mermaid.min.js
  - js/mermaid.js
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: diagram
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
repo_url: https://gitlab.com/limelight-networks/qa/ltf/ltf-projects/edgio-console-app
repo_name: qa/ltf/ltf-projects/edgio-console-app
edit_uri: edit/master/docs/

